### PR TITLE
Update checkout.tpl

### PR DESCRIPTION
**Pull request by osworx**
Changing alert message to be able to use formatting.
checkout_agree_terms_htmlspecialchars

checkout_agree_terms_html_entity_decode

### CODE REVIEW

**Comment by osworx** [comment]
While such things should be done earlier in the controller - or not?

**Comment by denisdulici** [comment]
Exactly Michael, it must be done in the controller. Could you plz update the PR by changing it accordingly?

**Comment by osworx** [comment]
Have seen, that such code is at several places.
Should I change all?

**Comment by denisdulici** [comment]
I'm not able to find any other in front-end, where is that exactly?

**Pull request closed without merging**
