### PR TITLE
#206 Fixing consistency for # (Order ID #)

### PR DESCRIPTION
**Pull request by syntaxerror**
#206 Fixing consistency for # (Order ID #), and moving it into language files as it's a English thing to use.

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Rune for PR. I agree with the move to language files but not with "Order ID: #". Instead of, "Order ID:" is enough, there is no need for # at all. Can you please remove it from language files so I could merge this PR?

**Comment by syntaxerror** [comment]
OK, will do - was just afraid that some would like to keep it. Personally I agree it's not needed.

**Comment by syntaxerror** [comment]
Btw! What do you think about the space, add it back in code, or keep it in language files?
I see there is several language strings including a space after : in language files already, while it's not the best way to have it, it works somehow.

**Comment by denisdulici** [comment]
I think it should be in tpl, not language files.

**Comment by syntaxerror** [comment]
Then there is quite much to clean up in the system, and I think it's better to just close this and start over then. I'll look at it...

**Comment by denisdulici** [comment]
I would prefer the Order ID # PR to be separated from the space one.

**Comment by syntaxerror** [comment]
They are related, and I would have to add it back anyway. If just changing language files in this PR now you would get "Order ID:xx". Really not easy to make all happy... :)

**Comment by denisdulici** [comment]
I didn't mean space changes for files within this PR, they're OK :wink:

**Pull request merged**
