### PR TITLE
Fix $languages to $languages['code'] for change lang.

### PR DESCRIPTION
**Pull request by bahramdavoodi**

### CODE REVIEW

**Comment by cuneytsenturk** [comment]
Bahram, this seems to break the system instead of fixing?

**Comment by bahramdavoodi** [comment]
cuneytsenturk, this is fix for change language.
for example you have a site with 2 or 3 language. if you set default language to persian or ..., site opened with english language. you can try this. for test you have to clear cookies.

**Comment by syntaxerror** [comment]
@bahramdavodi - is this related to browser detection, and this https://arastta.org/forum/multi-store,-languages-and-currencies#reply-734 ?

**Comment by bahramdavoodi** [comment]
I think this is same but this fix is very important for change languages.

**Comment by denisdulici** [comment]
This may have fixed something accidentally Bahram but getBrowserLangCode function wants it to be an array, not string:
https://github.com/arastta/arastta/blob/master/system/library/utility.php#L127

**Comment by bahramdavoodi** [comment]
@denisdulici but this file is getBrowserDefaultLanguage function not getBrowserLangCode.
in the function getBrowserDefaultLanguage we need string.
https://github.com/arastta/arastta/blob/master/system/library/utility.php#L76

yes i know getBrowserLangCode function is array.

if you want i can take photo from this problem and i show to you.

**Comment by bahramdavoodi** [comment]
for example : 
now default language system is persian. but site opened with english language.
if i change language to persian site is ok. but for first visit site open with english language. this problem is for all visitor.

untitled

**Comment by syntaxerror** [comment]
I agree that the sites default language should be loaded before browsers default, else there is not much use of having a setting for default language in the system.

**Comment by denisdulici** [comment]
That is not a bug, it's a feature. It gets your browser language. Default one is used when the browser language is not available on that site.

getBrowserDefaultLanguage method sends it to getBrowserLangCode.

**Comment by syntaxerror** [comment]
It's true Denis, but still there should be a force option, so the store owner can decide what they want per store/domain.

**Comment by denisdulici** [comment]
We may discuss that Rune but not this PR.

The Language Filter plugin of Joomla has such an option asking for the language selection for new visitors: 1) Site Language 2) Browser Settings

**Pull request closed without merging**
