### PR TITLE
Fixing #398 for core included payment modules

### PR DESCRIPTION
**Pull request by syntaxerror**

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Rune for the PR. However, this will override the "Complete Order Status" in the Settings => Option tab. Notification emails are sent only if the order status matches one of the selected statuses there.

**Comment by syntaxerror** [comment]
Damn ... forgot about that setting. But then there probably is a "reversed" problem with some modules always sending anyway: https://arastta.org/forum/strange-email-problem

EDIT: If this override shouldn't be possible, the addOrderHistory function might need a change. But personally I would prefer having this setting in each payment module (always send or send on status), instead of having it as a global setting.

**Comment by syntaxerror** [comment]
On the other hand, when I shop online, I always expect a order confirmation to ensure all went well. If I don't get it, and don't have registered an account, I would need to contact the store to check what went wrong. Thus I'm not sure when there is a need for not sending this.

**Comment by gepeixoto** [comment]
I agree with Rune, when I shop online, I always expect an order confirmation.
So, I added following code at start of addOrderHistory function, just after `if ($order_info) {`:

`if (!$order_info['order_status_id'] && $order_status_id) {`
`$notify = true;`
`}`

This way, if the history being added belongs to a new order, $notify = true.

**Comment by cuneytsenturk** [comment]
Closing this for now as have to delete the 1.3-dev branch.

**Comment by syntaxerror** [comment]
There must be a better way, than closing ongoing discussions?
Doesn't GitHub support changing target branch?
Else we would need to always send all PR's to main branch, as this isn't good ...

**Pull request closed without merging**
