### PR TITLE
Fix - Order mail having Arastta hardcoded

### PR DESCRIPTION
**Pull request by syntaxerror**
Changed Arastta to {store_name}

TODO: Fix all those texts to fit better for each status and use. Also "Thank you for your interest in {store_name} products." should probably rather be "Thank you for your interest in {store_name}'s products." (as in "Thank you for your interest in Arastta's products."). But that is beyond this simple and quick fix to make it match ...

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Rune for your contribution. Can you please send it again to 1.5-dev branch as master is frozen atm?

**Comment by syntaxerror** [comment]
Hi Denis, there is no need to close or resend, it's just a matter of changing base branch since it ended up in the wrong one. I'll do it from here right now ... :)

**Comment by denisdulici** [comment]
Sorry Rune, didn't know that 😢 I'm getting older..

**Comment by syntaxerror** [comment]
Ha ... I'm 10 years older than you Denis, it's just me getting old and wise. Hehe ... ;)

**Pull request merged**
