### PR TITLE
Fixing #493 (and improving #406)

### PR DESCRIPTION
**Pull request by syntaxerror**
Fixing #493 (and improving #406)

Note! I would prefer renaming "date", but that would break design compatibility ...

### CODE REVIEW

**Comment by gepeixoto** [comment]
Isn't easiest (and more viable) do the logic just in controller:
`'date'  => ($result['date_modified'] != 0) ? $result['date_modified'] : $result['date_added'],`
By keeping the logic in controller is better for performance and don't require template changes.

**Comment by syntaxerror** [comment]
If it's tested and works +1
Most templates would still need fixing though, because of wrong date format.

**Comment by gepeixoto** [comment]
Yes, Rune, it will work just like your previous proposal.

**Comment by cuneytsenturk** [comment]
Thanks Rune and Gedielson,

**Pull request merged**
