### PR TITLE
fixed #23 - error message on failure to delete install dir

### LINKED ISSUE #23: Show a proper warning if the install folder was not removed
http://arastta.org/forum/install-error

### PR DESCRIPTION
**Pull request by brettwhiteman**
Also fixed indentation

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Brett. The indentation seems not correct for JS code:

```
        complete: function() {
        $('.loading-bar').delay(500).fadeOut('slow');
        },
```

**Comment by brettwhiteman** [comment]
Sorry  - tried to clean it up automatically with my editor. Have fixed it now.

**Comment by denisdulici** [comment]
Great. There are 3 other points here:

1) model->removeInstall function always returns true:
https://github.com/arastta/arastta/blob/master/install/model/main.php#L244

2) After the changes in the Filesystem class, the following code would not catch:
https://github.com/arastta/arastta/blob/master/install/model/main.php#L240

3) Instead of alert, why not show as message in finish.tpl:

```
<div class="col-xs-12">
    <div class="text-center">
        <i class="fa fa-thumbs-o-up fa-4x"></i>&nbsp;<h4><?php echo $text_finish_header; ?></h4>
    </div>
</div>
<div class="col-xs-12" style="display:none;">
    <div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> <?php echo $error_remove_install; ?>
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
</div>
```

**Comment by brettwhiteman** [comment]
Thanks - I have updated the commit.

**Comment by denisdulici** [comment]
Thanks Brett.

**Pull request merged**
