### PR TITLE
Improving #429

### PR DESCRIPTION
**Pull request by syntaxerror**

### CODE REVIEW

**Comment by denisdulici** [comment]
What does this exactly do Rune? From what I can see, it changes $100 to USD 100, right?

**Comment by syntaxerror** [comment]
It fixes the bad display ref https://github.com/arastta/arastta/issues/429#issuecomment-215185817

Basically it removes the currencies prefix and suffix, and instead add the currency code.

**Comment by syntaxerror** [comment]
Don't merge this yet, even if you agree. There is a better way, fixing formating for all widgets and more, if we add the setlocale globally first. See discussion added in dev group Denis.

It would be working like something like this then:
setlocale(constant('LC_ALL'), 'nb_NO');
$data['total'] = $this->config->get('config_currency') . ' ' . $data['total'] . $suffix;

Before:
skjermbilde fra 2016-05-13 02-33-53

After:
skjermbilde fra 2016-05-13 02-33-09

**Comment by syntaxerror** [comment]
Redid the code, and it will work and be consistent for now without adding setlocale (witch should be fixed later globally though). This should be ready to merge as it is now, if found OK and agreed on.

**Comment by syntaxerror** [comment]
New merged/combined PR added replacing this.

**Pull request closed without merging**
