### PR TITLE
Fixing #769 - Replacing mCrypt with OpenSSL

### PR DESCRIPTION
**Pull request by syntaxerror**
Fixing #769 - Replacing mCrypt with OpenSSL
* needs more testers

### CODE REVIEW

**Comment by denisdulici** [comment]
Does this work on current installations or only new ones?

**Comment by syntaxerror** [comment]
That is a great question, and that's why it should be tested more.

I'm not sure what it actually could break, but maybe you who know the system better can give us some clues?

**Comment by syntaxerror** [comment]
@denisdulici - Did you not know what could break, meaning what should be tested closely according to your opinion and knowledge?

Anyhow, also the form would need fixing: https://github.com/arastta/form/issues/4

**Comment by denisdulici** [comment]
Going to test this by today Rune.

**Comment by denisdulici** [comment]
Tested and it works fine. Thanks Rune for the contribution.

**Pull request merged**
