### PR TITLE
Update CREDITS.txt

### PR DESCRIPTION
**Pull request by budgetneon**
See http://i.imgur.com/bWADpvi.png

### CODE REVIEW

**Comment by denisdulici** [comment]
Thank you @budgetneon for your interest on Arastta. However, I'm sorry but your claim is not valid, Arastta code has nothing to do with yours. Every (OC) developer knows that cache must be disabled if page contains dynamic content such as items in cart or user/customer/affiliate information or other cases. Also, your code doesn't know that cache must be disabled when there is a tracking code or a redirection in the URL, Arastta does.

PS: The full code of classes being of concern:
https://github.com/arastta/arastta/blob/master/system/library/pagecache.php
https://github.com/budgetneon/v2pagecache/blob/master/upload/system/library/v2pagecache.php

**Comment by budgetneon** [comment]
Yes, you refactored/rewrote it. 

http://i.imgur.com/bWADpvi.png shows pretty clearly, though, what codebase you started from. 

I didn't expect you to come clean, as you've been caught in the past, but I also wasn't going to let it go by without calling it out.

Cheers.

**Comment by budgetneon** [comment]
"Also, your code doesn't know that cache must be disabled when there is a tracking code or a redirection in the URL"

I suppose, if a redirection returns an http response code of 200, but that would be odd.  

Cheers again.

**Comment by budgetneon** [comment]
Oh, and it's not that you're testing for the same conditions that's interesting.  What's interesting is that you're testing in the same exact order, with very similar comments above each test.  That's not a coincidence.

**Comment by budgetneon** [comment]
http://i.imgur.com/bWADpvi.png speaks for itself.

**Comment by denisdulici** [comment]
You're wrong, it's not the same conditions, not same order and not same comments.

The code speeks by itself so there is no need for anyone else to defend it!

**Comment by budgetneon** [comment]
"You're wrong, it's not the same conditions, not same order and not same comments."

Uh, yeah.  Why do you keep deleting comments and the link to  http://i.imgur.com/bWADpvi.png then?

**Comment by budgetneon** [comment]
See http://i.imgur.com/bWADpvi.png

**Comment by budgetneon** [comment]
See http://i.imgur.com/bWADpvi.png

**Comment by budgetneon** [comment]
See http://i.imgur.com/bWADpvi.png

**Comment by denisdulici** [comment]
Last comment: Your image is available since the first message!!!

**Comment by budgetneon** [comment]
Lol.   Say, have you ever been caught doing this sort of stuff before, like perhaps with a Joomla / Opencart integration?

**Pull request closed without merging**
