### PR TITLE
Tinymce 423

### PR DESCRIPTION
**Pull request by osworx**
Updated TinyMCE to latest 4.2.3
New plugin codemirror
Removed not needed plugin code (already in main jquery.tinmyce.js)
Updated skins
Added languages (langs)

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Michael for updating the PR :smirk: 

1) The interface is not translated
2) Not able to see codemirror

**Comment by osworx** [comment]
For both another PR will be required because another thing and has nothing todo with the editor update.

**Comment by denisdulici** [comment]
If those has nothing to do with editor update then we should remove them from this PR.

**Comment by osworx** [comment]
Guess you mix here 2 completely different things - should be discussed internal.

**Pull request closed without merging**
