### PR TITLE
Note about clearing cache on Update success & Backup restore

### PR DESCRIPTION
**Pull request by syntaxerror**
A reminder to clear the cache after update and backup restore, to ensure all is loaded correctly.

### CODE REVIEW

**Comment by cuneytsenturk** [comment]
Hi Rune,

Why do not we clear cache? I did not like to message :grimacing:

I think, We can use new feature 'Tool->Cache manager'.

**Comment by syntaxerror** [comment]
Not sure if I understand you here, but when the store is updated or restored to a previous backup the user  really should remember to clear the cache, else there will be trouble.

If you're able to make the cache clear automatically on update and backup restore, that is sure better - but for now users needs to remember doing this. Thus it's a good thing to remind them to do it ... :)

**Comment by syntaxerror** [comment]
Ah, you're thinking about the new cache management added by Denis for 1.5: https://github.com/arastta/arastta/commit/8caf313a8d138242bec877b09304e62c62074dcb

I simply forgot it was there.

Sure we can use it, but we still need to remind the users about using it, I'll change the text asap.

**Comment by cuneytsenturk** [comment]
Thanks Rune.

**Pull request merged**
