### PR TITLE
Update header.tpl

### PR DESCRIPTION
**Pull request by osworx**
Reordered header scripts and links
Added title text to contact link
Changed Checkout icon

### CODE REVIEW

**Comment by denisdulici** [comment]
Applying these changes will break vQmod/OCMod extensions that interfere in that part.

**Comment by denisdulici** [comment]
Also, it would be better if the controller,language and tpl file would be all in one pull request as they are dependent to each other.

**Comment by osworx** [comment]
That would mean that Arastta will be ever depend in OC?
Second, adding only the title and changing the icon (the current is sh**) is not that big change!
Which mods can depend on these 2?

**Comment by denisdulici** [comment]
I didn't say OC but vQmod/OCMod extensions and it's very early to talk about ever.
Maybe not on those 2 but definitely on the 3rd one.

**Comment by osworx** [comment]
Okay, fact is that Arastta should not make same errors OC is doing.
header.tpl is since 1.4 crappy.
css and scripts should grouped together and in correct order (good that you did not make the PR, because I did it wrong): first css, then script.

One PR: how to do that (without any command line)?

**Comment by denisdulici** [comment]
That's why I'm saying this, to not make same errors of OC by breaking extension compatibility.

You should commit all changes then create the pull request.

**Pull request closed without merging**
