### PR TITLE
Command line interface

### PR DESCRIPTION
**Pull request by matt-t-d**
Added a CLI to Arastta.
Had to add quite a few workarounds that I'm not particularity happy with but e.g. defining HTTP_SERVER to stop some error messages. 

Wasn't sure if you want to use this and if this is the way you would want it implemented but if you have any thoughts let me know

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Matthew for this wonderful contribution. We just need to fix/change the followings:
1. library/client.php : Can you please remove isAdmin, isCatalog and isInstall functions as your __callStatic method is enough. Also, can you please apply the coding standards to __callStatic method?
2. library/command/command.php : Must be relocated but I'll do that after merging your PR.
3. I get the following error when I try to run CLI. It gives same for cache:clear command.

**Comment by matt-t-d** [comment]
Thanks, I've made the changes and applied the coding standards.

The error was from checking if a function result was empty directly (which works in newer PHP versions now)

**Comment by denisdulici** [comment]
Thanks Matthew.

**Comment by denisdulici** [comment]
Example command for Arastta installation:

```
php cli install --db_username="root" --db_database="arastta-cli" --store_email="sales@mail.com" --admin_email="admin@mail.com" --admin_password="123456"
```

What do you think about the demo data option, for CLI installations, should it be checked by default or not?

**Comment by matt-t-d** [comment]
I think it should be off by default for a couple of reasons.
I think it makes a bit more sense to use --install_demo_data as a flag rather than --install_demo_data=false.
Also, people using the CLI are probably more comfortable with Arastta and may not need it.

Another option which might work better is to use the cli interactively and ask the user if they want to install the demo data as part of the install process.

**Pull request merged**
