### PR TITLE
Option to not install demo data

### PR DESCRIPTION
**Pull request by brettwhiteman**
You may want to review the tables I have marked as 'demo data'

### CODE REVIEW

**Comment by denisdulici** [comment]
I think we may improve this a little:

1) Separate the CREATE and INSERT queries to different files like tables.sql + demo.sql. Keep in mind that some INSERT queries such as for country must be in the tables.sql file.

2) The installation process must be as simple as possible so such options should be hidden by default. We can use collapse for such a purpose: http://getbootstrap.com/javascript/#collapse-example

Something like Advanced settings:


What do you think?

**Comment by brettwhiteman** [comment]
Good ideas. I'll separate the SQL files and adjust the frontend.

I'm also adding another commit to remove the demo images if needed.

**Comment by denisdulici** [comment]
Great Brett. Separating SQL files will also allow us to make the demo data multilingual in the future versions :smirk:

**Comment by brettwhiteman** [comment]
How's this?

**Comment by denisdulici** [comment]
Very nice Brett. Changing the style as the following will make the button fit the page standards:

``` css
.btn-expand-down {
    width: 30px;
    height: 30px;
    padding: 0px;
    border-radius: 15px;
    background-color: transparent;
    outline: medium none;
    border: 1px solid #ccc;
    color: #333;
}

.fa-chevron-up {
    margin-bottom: 5px;
}
```

I installed without sample data and it worked fine except the "Information" footer links because of the url_alias table being empty. I suppose we should also move those information pages to demo.sql and update the setting table in case no data is installed. Set the following keys to 0:
- config_account_id
- config_checkout_id
- config_affiliate_id
- config_return_id

**Comment by denisdulici** [comment]
Brett, can you please send the PR to 1.1-dev branch?

**Pull request closed without merging**
