### PR TITLE
 Rename robots.txt to robots.txt.dist #336

### PR DESCRIPTION
**Pull request by syntaxerror**

### CODE REVIEW

**Comment by denisdulici** [comment]
Thanks Rune for the PR. Can you please also "try" to rename it during installation:
https://github.com/joomla/joomla-cms/commit/1f37e4c7ac254b30b7a1ce8bdd7dd0013d73370d

**Comment by syntaxerror** [comment]
> Can you please also "try" to rename it during installation

No, sorry. Anyhow a robot.txt isn't required for a site to work, most users will probably be better without it if they have no clue it's there, and what it does, or how to modify it.

It's actually a bigger problem that it's get overwritten for those knowing, and have modified it, so it's the priority here.

**Comment by EnesErtugrul** [comment]
I agree to have robots.txt file as robots.txt.dist by default. This will prevent the overrides for the modified ones.

But if we have this file in the core, it must be renamed for the first and clean installations. Otherwise we don't need to include this file in the core, since it's very easy to create robots.txt file for advanced users. But it's a feature for newbies which comes with default definitions.

**Comment by syntaxerror** [comment]
I disagree on the importance for auto-renaming in this PR, as it's a bigger problem that updates now overwrites existing and modified versions of it. Anyone who wants to work on that can though do so, here, or start a new issue for it.

Anyhow, following this logic you should also remove or rename htaccess.txt

They are templates/examples, noting more, nothing less.

**Comment by EnesErtugrul** [comment]
It's different for htaccess.txt file since user need to have mod_rewrite enabled on his/her server to rename it. So we cannot automise it. 

So I'm not in favor of this PR. Because we will have a useless file (robots.txt.dist) for most of the users, it's better to remove it from the core. Experts or advanced users always can create it theirselves.

As a result my opinion:
1- We can keep current file system because it provides a default robots.txt definition
2- We can implement an update-proof robots.txt.dist file but which will be renamed for the fresh installations.

**Comment by syntaxerror** [comment]
We disagree (it's t.ex. possible to check for mod_rewrite too), but ...

+1 for removing it then, unless someone writes the needed code for renaming. The importance here is to avoid it being overwritten on updates, keeping it as it is isn't an option.

Btw! Another thing to add is the problems it will cause for those not understanding it, as it will make mobile tests fail if they change templates, or add mods that need additions to allow different folders. If it's just a dist file they probably will look closer at it at some point.

**Comment by syntaxerror** [comment]
Just for the record:
When installing t.ex. Joomla through Softaculous or similar, the file is still named robots.txt.dist

**Comment by cuneytsenturk** [comment]
Closing this for now as have to delete the 1.3-dev branch.

**Comment by syntaxerror** [comment]
Issue #336 reopened then.

**Pull request closed without merging**
